import test from 'node:test';
import assert from 'node:assert/strict';
import { BridgeClient } from '../../apps/web/src/platform/bridge-client.ts';
const initial={session:'session_123',epoch:0};
const reply=request=>({...request,ok:true,outcome:'completed',value:'saved'});
test('fire-and-forget Expo handle receives a separately correlated asynchronous reply',async()=>{let sent;const client=new BridgeClient(()=>initial,request=>{sent=request;});let settled=false;const result=client.request('snapshot').then(value=>{settled=true;return value;});await Promise.resolve();assert.equal(settled,false);assert.equal(client.receive(reply(sent)),true);assert.equal((await result).value,'saved');client.dispose();});
test('foreign session/id replies cannot settle a pending mutation',async()=>{let sent;const client=new BridgeClient(()=>initial,request=>{sent=request;});const result=client.request('settings',{key:'fontSize',value:24});assert.equal(client.receive({...reply(sent),session:'foreign_123'}),false);assert.equal(client.receive({...reply(sent),id:'foreign_123'}),false);client.receive(reply(sent));assert.equal((await result).outcome,'completed');client.dispose();});
test('late completed replies retain outcome but become stale across account ABA',async()=>{let scope=initial,sent;const client=new BridgeClient(()=>scope,request=>{sent=request;});const result=client.request('settings');scope={...initial,epoch:2};client.receive(reply(sent));const value=await result;assert.equal(value.stale,true);assert.equal(value.outcome,'completed');client.dispose();});
test('send failure and teardown never imply safe automatic mutation replay',async()=>{const a=new BridgeClient(()=>initial,()=>{throw new Error('not ready');});await assert.rejects(a.request('settings'),/not ready/);let sent;const b=new BridgeClient(()=>initial,request=>{sent=request;});const pending=b.request('settings');b.dispose();await assert.rejects(pending,/saved outcome must be reconciled/);assert.equal(b.receive(reply(sent)),false);});
