packages:
  - apps/*
allowBuilds:
  esbuild: true
  protobufjs: false
  svelte-preprocess: true
  unrs-resolver: true
patchedDependencies:
  '@expo/dom-webview@57.0.1': patches/reader-dom/expo-dom-webview-57.0.1.patch
