import process from 'node:process';
import { writeFileSync, readFileSync } from 'node:fs';
import { availableThemes, themeProperties } from '../../apps/web/src/lib/data/theme-option.ts';
const rules = [];
for (const id of availableThemes.keys()) {
  const selector =
    id === 'manabi-theme' ? ':root, :root[data-theme="manabi-theme"]' : `:root[data-theme="${id}"]`;
  rules.push(`${selector} {`);
  for (const mode of ['light', 'dark'])
    for (const [key, value] of Object.entries(themeProperties(id, mode))) {
      rules.push(`  --${mode}-${key}: ${value};`);
    }
  rules.push('}');
}
const css =
  '/* Generated by tools/appearance/generate-css.mjs. Edit theme-option.ts instead. */\n' +
  rules.join('\n') +
  '\n';
const path = new URL('../../apps/web/src/lib/appearance/palettes.scss', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== css)
    throw new Error(
      'Appearance palettes are stale; run node --experimental-strip-types tools/appearance/generate-css.mjs'
    );
} else writeFileSync(path, css);
