/** @license BSD-3-Clause */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const root = fileURLToPath(new URL('..', import.meta.url));
const app = path.join(root, 'apps/web');
const require = createRequire(path.join(app, 'package.json'));
const sass = require('sass');
// Sass imports are compiled explicitly; Metro's Sass support does not follow @use.
const result = sass.compile(path.join(app, 'src/app.scss'), { style: 'expanded' });
const fontFaces = [...result.css.matchAll(/@font-face\s*\{[\s\S]*?\}/g)].map(match => match[0]);
const fontPaths = [...new Set(fontFaces.flatMap(face => [...face.matchAll(/url\(["']?\$lib\/([^"')]+)["']?\)/g)].map(match => match[1])))];
const imports = fontPaths.map((file, index) => `import font${index} from '../lib/${file}';`).join('\n');
const faces = fontFaces.map(face => {
  const pieces = []; let end = 0;
  for (const match of face.matchAll(/url\(["']?\$lib\/([^"')]+)["']?\)/g)) { pieces.push(JSON.stringify(face.slice(end, match.index))); pieces.push(`'url("' + String(font${fontPaths.indexOf(match[1])}) + '")'`); end = match.index + match[0].length; }
  pieces.push(JSON.stringify(face.slice(end))); return pieces.join(' + ');
});
await fs.writeFile(path.join(app, 'src/runtime/font-assets.ts'), `/** Generated by prepare-expo.mjs. @license BSD-3-Clause */\n${imports}\nexport const bundledFontCSS = [${faces.join(',\n')}].join('\\n');\n`);
await fs.writeFile(path.join(app, 'src/app.generated.css'), result.css.replace(/@font-face\s*\{[\s\S]*?\}/g, ''));

// Expo embeds public assets into the Android binary for DOM components.
// EAS Update is disabled: asset updates require a new reviewed binary.
await fs.rm(path.join(app, 'public'), { recursive: true, force: true });
await fs.mkdir(path.join(app, 'public'), { recursive: true });
await fs.cp(path.join(app, 'static'), path.join(app, 'public'), { recursive: true, filter: source => (process.env.EXPO_PUBLIC_ENABLE_VIDEO_LEARNING ?? process.env.VITE_ENABLE_VIDEO_LEARNING) === 'true' || !source.startsWith(path.join(app, 'static/moss')) });

// Keep the checked-in reader CSS synchronized with the retained scoped Sass source.
await fs.writeFile(path.join(app, 'src/reader-react/reader.css'), sass.compile(path.join(app, 'src/reader-react/reader.scss')).css);
